[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.20"
exclude = ["contracts/legacy/**", "**/WETH.sol"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]